apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappui
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todoappui
  template:
    metadata:
      labels:
        app: todoappui
    spec:
      containers:
      - name: todoappui
        image: jaiswal4656/todo18jan
        ports:
        - containerPort: 80
